### ISSUE TITLE
Bitcoin Miner, Idle Miner, ZBDWatchAndEarn: Image list to check for missing screenshots

### ISSUE THREAD

**Issue by Alfred-Langer** [Alfred-Langer/App-Automation-For-Cash#4]
All scripts should have a designated list of images that need to be present in the script's associated folder within Screenshots. Screenshots is not uploaded to the repo as each image is different depending on the OS, resolution, and other display settings of the user. That being said, every user is going to need the same list of images in order for the script to run.

Todo: Create a list of the required screenshots/images for each script to run. Add some functionality in each script that will search for these images and ensure they are present before running.

**Comment by jjyutm4532** [comment]
Hello, I tried to solve the issue.

This is what I did:

Added a function to verify required screenshots are present before running the main script. This includes creating a list of required images and checking for their existence.

You can review changes in this commit: https://github.com/jjyutm4532/Alfred-Langer-App-Automation-For-Cash-4/commit/63108f2f09c78acb64c499825510a45887901642.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
